language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: lorey
  password:
    secure: ilKZ9qDwnHVzQC1b1odIUSLphTQ0wWtXNOAs6tZ63MFd4oHFactVihuryuH66cj2mzXuXcRghWe91MT4EjOGUa+he68oHTCp2cV6HwEP+6b+BO6JZXeCQ0luxmFqm0TFbssfmt20ilmZgBiaswu0QliYrKW7yUocsGHqXwfbhaQL3b40mMTG8a7IB9f4hiU7wafbV0JbHZWn5uhlmPQEmdxxMlrhVkTytz9lIN4GLl2wpPskulKT7uwBjYGxQWlsvEROfxjom7AWkEMwsxp3Ht3jG5H3YW/gl9l9o1DJSRXHwFSCY17HtMXa57G3vHIpLl7NgMhLkPfC01fKYkhex+DzngfTpZ41zKrVRaHjKB4RHNTYlQRp/cPLTVlHG6b5h+TFVy7RgYOMkrhCf4DVBpgWTbLi2Eav+t2bnSqvw8PQiFUfRKCaM+8ARa3oAUixIZxIqa9R7fmYopQraDkYyb4ydOK9vQtaATgRYEiIFPDJfsEaRNOKh8ovnkiZvnx/lYcYxt4vtuRCW53Gf5HzGGnEmOBCjQ1v29XlQsjPNIPV4GTfA7Ac8ds6ncp98pU628OjhIFlsELpm3iBK0s4cub7CM9dzcZtoMark9uYyRFFDuWAy5k8hrx15rf7RW9tLYw6TWUSzs7iRBYf8QQoY5hjUACBj928e892iNTiNrk=
  on:
    tags: true
    repo: lorey/mlscraper
    python: 3.8
